name: Generate Snake Animation 🐍

on:
  schedule: # Runs every 12 hours
    - cron: "0 */12 * * *"
  workflow_dispatch: # Allow manual trigger

jobs:
  build:
    name: Build Snake Animation
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Generate Snake SVG
        uses: Platane/snk@v3
        with:
          github_user_name: Dhanushpthampi
          outputs: dist/snake.svg

      - name: Push Snake to GitHub Pages
        uses: crazy-max/ghaction-github-pages@v4
        with:
          target_branch: output
          build_dir: dist
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
